USE los;

-- cleanup
-- note the reverse order becase of keys
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS attempts;
DROP TABLE IF EXISTS competitors;
DROP TABLE IF EXISTS squads;
DROP TABLE IF EXISTS situations;
DROP TABLE IF EXISTS competitions;
DROP TABLE IF EXISTS competition_types;
DROP TABLE IF EXISTS competition_categories;
DROP TABLE IF EXISTS ranges;

-- create

CREATE TABLE IF NOT EXISTS ranges (
  ID int(11) NOT NULL AUTO_INCREMENT,
  NAME tinytext NOT NULL,
  LATITUDE decimal(15,12) NOT NULL,
  LONGITUDE decimal(15,12) NOT NULL,
  URL tinytext NOT NULL,
  ACTIVE tinyint(1) NOT NULL DEFAULT 1,
  CREATED_TS timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8 WITH SYSTEM VERSIONING;

CREATE TABLE IF NOT EXISTS competition_categories (
  ID int(11) NOT NULL AUTO_INCREMENT,
  CODE varchar(10) NOT NULL,
  NAME tinytext NOT NULL,
  CREATED_TS timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY UQ_COMPETITION_CATEGORY_CODE (CODE)
) DEFAULT CHARSET=utf8 WITH SYSTEM VERSIONING;

CREATE TABLE IF NOT EXISTS competition_types (
  ID int(11) NOT NULL AUTO_INCREMENT,
  CODE varchar(10) NOT NULL,
  NAME tinytext NOT NULL,
  CREATED_TS timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY UQ_COMPETITION_TYPE_CODE (CODE)
) DEFAULT CHARSET=utf8 WITH SYSTEM VERSIONING;

CREATE TABLE IF NOT EXISTS competitions (
  ID int(11) NOT NULL AUTO_INCREMENT,
  NAME tinytext NOT NULL,
  EVENT_DATE date NOT NULL,
  RANGE_ID int(11) NOT NULL,
  CATEGORY_ID int(11) NOT NULL,
  TYPE_ID int(11) NOT NULL,
  CREATED_TS timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  KEY FK_COMPETITIONS_ranges (RANGE_ID),
  KEY FK_competitions_competition_categories (CATEGORY_ID),
  KEY FK_competitions_competition_types (TYPE_ID),
  CONSTRAINT FK_COMPETITIONS_ranges FOREIGN KEY (RANGE_ID) REFERENCES ranges (ID),
  CONSTRAINT FK_competitions_competition_categories FOREIGN KEY (CATEGORY_ID) REFERENCES competition_categories (ID),
  CONSTRAINT FK_competitions_competition_types FOREIGN KEY (TYPE_ID) REFERENCES competition_types (ID)
) DEFAULT CHARSET=utf8 WITH SYSTEM VERSIONING;

CREATE TABLE IF NOT EXISTS situations (
  ID int(11) NOT NULL AUTO_INCREMENT,
  NUMBER int(2) NOT NULL,
  NAME tinytext NOT NULL,
  COMPETITION_ID int(11) NOT NULL,
  CREATED_TS timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY UQ_SITUATION_NUMBER (NUMBER, COMPETITION_ID),
  KEY FK_situations_competition (COMPETITION_ID),
  CONSTRAINT FK_situations_competition FOREIGN KEY (COMPETITION_ID) REFERENCES competitions (ID)
) DEFAULT CHARSET=utf8 WITH SYSTEM VERSIONING;

CREATE TABLE IF NOT EXISTS squads (
  ID int(11) NOT NULL AUTO_INCREMENT,
  NUMBER int(2) NOT NULL,
  NAME tinytext NOT NULL,
  COMPETITION_ID int(11) NOT NULL,
  CREATED_TS timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY UQ_SQUAD_NUMBER (NUMBER, COMPETITION_ID),
  KEY FK_squads_competition (COMPETITION_ID),
  CONSTRAINT FK_squads_competition FOREIGN KEY (COMPETITION_ID) REFERENCES competitions (ID)
) DEFAULT CHARSET=utf8 WITH SYSTEM VERSIONING;

CREATE TABLE IF NOT EXISTS competitors (
  ID int(11) NOT NULL AUTO_INCREMENT,
  FIRST_NAME tinytext NOT NULL,
  LAST_NAME tinytext NOT NULL,
  NICKNAME tinytext NULL,
  EMAIL tinytext NOT NULL,
  LICENCE tinytext NOT NULL,
  SQUAD_ID int(11) NOT NULL,
  CREATED_TS timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  KEY FK_competitors_squad (SQUAD_ID),
  CONSTRAINT FK_competitors_squad FOREIGN KEY (SQUAD_ID) REFERENCES squads (ID)
) DEFAULT CHARSET=utf8 WITH SYSTEM VERSIONING;

CREATE TABLE IF NOT EXISTS attempts (
  ID int(11) NOT NULL AUTO_INCREMENT,
  COMPETITOR_ID int(11) NOT NULL,
  SITUATION_ID int(11) NOT NULL,
  CREATED_TS timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  KEY FK_attempts_competitor (COMPETITOR_ID),
  KEY FK_attempts_situation (SITUATION_ID),
  CONSTRAINT FK_attempts_competitor FOREIGN KEY (COMPETITOR_ID) REFERENCES competitors (ID),
  CONSTRAINT FK_attempts_situation FOREIGN KEY (SITUATION_ID) REFERENCES situations (ID)
) DEFAULT CHARSET=utf8 WITH SYSTEM VERSIONING;

CREATE TABLE IF NOT EXISTS users (
  ID int(11) NOT NULL AUTO_INCREMENT,
  LOGIN tinytext NOT NULL,
  PASSWORD tinytext NOT NULL,
  ACTIVE tinyint(1) NOT NULL DEFAULT 1,
  CREATED_TS timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
)  DEFAULT CHARSET=utf8 WITH SYSTEM VERSIONING;