DROP DATABASE IF EXISTS los;
CREATE DATABASE IF NOT EXISTS los /*!40100 DEFAULT CHARACTER SET utf8 */;
USE los;

DROP TABLE IF EXISTS ranges;
CREATE TABLE IF NOT EXISTS ranges (
  ID int(11) NOT NULL AUTO_INCREMENT,
  NAME tinytext NOT NULL,
  LATITUDE decimal(10,7) NOT NULL,
  LONGITUDE decimal(10,7) NOT NULL,
  ACTIVE tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (ID)
) DEFAULT CHARSET=utf8;