language: go

go:
  - 1.11.x

before_install:
  - go get -u github.com/onsi/ginkgo/ginkgo

script:
  - go test $(go list ./... | egrep -v '/vendor/')
  - ./scripts/build/coverall.sh #go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
