// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi LOS data server
This is a data server for LOS shooting competition.

Terms Of Service:

http://todo/terms/


    Schemes:
      https
    Host: todo.los.server
    BasePath: /v1
    Version: 1.0.0
    License: GNU General Public License v3.0 https://www.gnu.org/licenses/gpl-3.0.html
    Contact: <todo@los.cz>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
