// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/krezac/los-server/models"
)

// GetUserByNameHandlerFunc turns a function with the right signature into a get user by name handler
type GetUserByNameHandlerFunc func(GetUserByNameParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserByNameHandlerFunc) Handle(params GetUserByNameParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetUserByNameHandler interface for that can handle valid get user by name params
type GetUserByNameHandler interface {
	Handle(GetUserByNameParams, *models.Principal) middleware.Responder
}

// NewGetUserByName creates a new http.Handler for the get user by name operation
func NewGetUserByName(ctx *middleware.Context, handler GetUserByNameHandler) *GetUserByName {
	return &GetUserByName{Context: ctx, Handler: handler}
}

/*GetUserByName swagger:route GET /user/{username} user getUserByName

Get user by user name

*/
type GetUserByName struct {
	Context *middleware.Context
	Handler GetUserByNameHandler
}

func (o *GetUserByName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUserByNameParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
