// Code generated by go-swagger; DO NOT EDIT.

package competition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	models "github.com/krezac/los-server/models"
)

// NewCreateCompetitionParams creates a new CreateCompetitionParams object
// no default values defined in spec.
func NewCreateCompetitionParams() CreateCompetitionParams {

	return CreateCompetitionParams{}
}

// CreateCompetitionParams contains all the bound params for the create competition operation
// typically these are obtained from a http.Request
//
// swagger:parameters createCompetition
type CreateCompetitionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Created competition object
	  Required: true
	  In: body
	*/
	Body *models.Competition
	/*ID of the range the competition is created for
	  Required: true
	  In: path
	*/
	RangeID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateCompetitionParams() beforehand.
func (o *CreateCompetitionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Competition
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body"))
	}
	rRangeID, rhkRangeID, _ := route.Params.GetOK("rangeId")
	if err := o.bindRangeID(rRangeID, rhkRangeID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindRangeID binds and validates parameter RangeID from path.
func (o *CreateCompetitionParams) bindRangeID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("rangeId", "path", "int64", raw)
	}
	o.RangeID = value

	return nil
}
