// Code generated by go-swagger; DO NOT EDIT.

package competition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/krezac/los-server/models"
)

// DeleteCompetitionHandlerFunc turns a function with the right signature into a delete competition handler
type DeleteCompetitionHandlerFunc func(DeleteCompetitionParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteCompetitionHandlerFunc) Handle(params DeleteCompetitionParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// DeleteCompetitionHandler interface for that can handle valid delete competition params
type DeleteCompetitionHandler interface {
	Handle(DeleteCompetitionParams, *models.Principal) middleware.Responder
}

// NewDeleteCompetition creates a new http.Handler for the delete competition operation
func NewDeleteCompetition(ctx *middleware.Context, handler DeleteCompetitionHandler) *DeleteCompetition {
	return &DeleteCompetition{Context: ctx, Handler: handler}
}

/*DeleteCompetition swagger:route DELETE /competitions/{competitionId} competition deleteCompetition

Delete competition

This can only be done by admin.

*/
type DeleteCompetition struct {
	Context *middleware.Context
	Handler DeleteCompetitionHandler
}

func (o *DeleteCompetition) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteCompetitionParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
