// Code generated by go-swagger; DO NOT EDIT.

package competition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCompetitionsHTMLParams creates a new GetCompetitionsHTMLParams object
// no default values defined in spec.
func NewGetCompetitionsHTMLParams() GetCompetitionsHTMLParams {

	return GetCompetitionsHTMLParams{}
}

// GetCompetitionsHTMLParams contains all the bound params for the get competitions Html operation
// typically these are obtained from a http.Request
//
// swagger:parameters getCompetitionsHtml
type GetCompetitionsHTMLParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*ID of shooting range to read the competitions for
	  Required: true
	  In: path
	*/
	RangeID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetCompetitionsHTMLParams() beforehand.
func (o *GetCompetitionsHTMLParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rRangeID, rhkRangeID, _ := route.Params.GetOK("rangeId")
	if err := o.bindRangeID(rRangeID, rhkRangeID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindRangeID binds and validates parameter RangeID from path.
func (o *GetCompetitionsHTMLParams) bindRangeID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("rangeId", "path", "int64", raw)
	}
	o.RangeID = value

	return nil
}
