// Code generated by go-swagger; DO NOT EDIT.

package competition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetCompetitionsParams creates a new GetCompetitionsParams object
// with the default values initialized.
func NewGetCompetitionsParams() GetCompetitionsParams {

	var (
		// initialize parameters with default values

		activeOnlyDefault = bool(true)
	)

	return GetCompetitionsParams{
		ActiveOnly: &activeOnlyDefault,
	}
}

// GetCompetitionsParams contains all the bound params for the get competitions operation
// typically these are obtained from a http.Request
//
// swagger:parameters getCompetitions
type GetCompetitionsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Return active only competitions
	  In: query
	  Default: true
	*/
	ActiveOnly *bool
	/*ID of shooting range to read the competitions for
	  Required: true
	  In: path
	*/
	RangeID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetCompetitionsParams() beforehand.
func (o *GetCompetitionsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qActiveOnly, qhkActiveOnly, _ := qs.GetOK("activeOnly")
	if err := o.bindActiveOnly(qActiveOnly, qhkActiveOnly, route.Formats); err != nil {
		res = append(res, err)
	}

	rRangeID, rhkRangeID, _ := route.Params.GetOK("rangeId")
	if err := o.bindRangeID(rRangeID, rhkRangeID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindActiveOnly binds and validates parameter ActiveOnly from query.
func (o *GetCompetitionsParams) bindActiveOnly(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetCompetitionsParams()
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("activeOnly", "query", "bool", raw)
	}
	o.ActiveOnly = &value

	return nil
}

// bindRangeID binds and validates parameter RangeID from path.
func (o *GetCompetitionsParams) bindRangeID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("rangeId", "path", "int64", raw)
	}
	o.RangeID = value

	return nil
}
