// Code generated by go-swagger; DO NOT EDIT.

package competition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCompetitionsHandlerFunc turns a function with the right signature into a get competitions handler
type GetCompetitionsHandlerFunc func(GetCompetitionsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCompetitionsHandlerFunc) Handle(params GetCompetitionsParams) middleware.Responder {
	return fn(params)
}

// GetCompetitionsHandler interface for that can handle valid get competitions params
type GetCompetitionsHandler interface {
	Handle(GetCompetitionsParams) middleware.Responder
}

// NewGetCompetitions creates a new http.Handler for the get competitions operation
func NewGetCompetitions(ctx *middleware.Context, handler GetCompetitionsHandler) *GetCompetitions {
	return &GetCompetitions{Context: ctx, Handler: handler}
}

/*GetCompetitions swagger:route GET /ranges/{rangeId}/competitions competition getCompetitions

List competitions for given shooting

Returns a list of competitions for shooting range

*/
type GetCompetitions struct {
	Context *middleware.Context
	Handler GetCompetitionsHandler
}

func (o *GetCompetitions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCompetitionsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
