// Code generated by go-swagger; DO NOT EDIT.

package competition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/krezac/los-server/models"
)

// GetCompetitionsHandlerFunc turns a function with the right signature into a get competitions handler
type GetCompetitionsHandlerFunc func(GetCompetitionsParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCompetitionsHandlerFunc) Handle(params GetCompetitionsParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetCompetitionsHandler interface for that can handle valid get competitions params
type GetCompetitionsHandler interface {
	Handle(GetCompetitionsParams, *models.Principal) middleware.Responder
}

// NewGetCompetitions creates a new http.Handler for the get competitions operation
func NewGetCompetitions(ctx *middleware.Context, handler GetCompetitionsHandler) *GetCompetitions {
	return &GetCompetitions{Context: ctx, Handler: handler}
}

/*GetCompetitions swagger:route GET /ranges/{rangeId}/competitions competition getCompetitions

List competitions for given shooting

Returns a list of competitions for shooting range

*/
type GetCompetitions struct {
	Context *middleware.Context
	Handler GetCompetitionsHandler
}

func (o *GetCompetitions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCompetitionsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
