// Code generated by go-swagger; DO NOT EDIT.

package competition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCompetitionsHTMLHandlerFunc turns a function with the right signature into a get competitions Html handler
type GetCompetitionsHTMLHandlerFunc func(GetCompetitionsHTMLParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCompetitionsHTMLHandlerFunc) Handle(params GetCompetitionsHTMLParams) middleware.Responder {
	return fn(params)
}

// GetCompetitionsHTMLHandler interface for that can handle valid get competitions Html params
type GetCompetitionsHTMLHandler interface {
	Handle(GetCompetitionsHTMLParams) middleware.Responder
}

// NewGetCompetitionsHTML creates a new http.Handler for the get competitions Html operation
func NewGetCompetitionsHTML(ctx *middleware.Context, handler GetCompetitionsHTMLHandler) *GetCompetitionsHTML {
	return &GetCompetitionsHTML{Context: ctx, Handler: handler}
}

/*GetCompetitionsHTML swagger:route GET /ranges/{rangeId}/competitions/html competition getCompetitionsHtml

List competitions for given shooting range as HTML page

Returns a list of competitions for shooting range as HTML page

*/
type GetCompetitionsHTML struct {
	Context *middleware.Context
	Handler GetCompetitionsHTMLHandler
}

func (o *GetCompetitionsHTML) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCompetitionsHTMLParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
