// Code generated by go-swagger; DO NOT EDIT.

package competition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/krezac/los-server/models"
)

// NewUpdateCompetitonParams creates a new UpdateCompetitonParams object
// no default values defined in spec.
func NewUpdateCompetitonParams() UpdateCompetitonParams {

	return UpdateCompetitonParams{}
}

// UpdateCompetitonParams contains all the bound params for the update competiton operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateCompetiton
type UpdateCompetitonParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Updated competition object
	  Required: true
	  In: body
	*/
	Body *models.Competition
	/*ID of competition to update
	  Required: true
	  In: path
	*/
	CompetitionID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateCompetitonParams() beforehand.
func (o *UpdateCompetitonParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Competition
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body"))
	}
	rCompetitionID, rhkCompetitionID, _ := route.Params.GetOK("competitionId")
	if err := o.bindCompetitionID(rCompetitionID, rhkCompetitionID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCompetitionID binds and validates parameter CompetitionID from path.
func (o *UpdateCompetitonParams) bindCompetitionID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("competitionId", "path", "int64", raw)
	}
	o.CompetitionID = value

	return nil
}
