// Code generated by go-swagger; DO NOT EDIT.

package competition

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
	models "github.com/krezac/los-server/models"
)

// UpdateCompetitonHandlerFunc turns a function with the right signature into a update competiton handler
type UpdateCompetitonHandlerFunc func(UpdateCompetitonParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateCompetitonHandlerFunc) Handle(params UpdateCompetitonParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateCompetitonHandler interface for that can handle valid update competiton params
type UpdateCompetitonHandler interface {
	Handle(UpdateCompetitonParams, *models.Principal) middleware.Responder
}

// NewUpdateCompetiton creates a new http.Handler for the update competiton operation
func NewUpdateCompetiton(ctx *middleware.Context, handler UpdateCompetitonHandler) *UpdateCompetiton {
	return &UpdateCompetiton{Context: ctx, Handler: handler}
}

/*UpdateCompetiton swagger:route PUT /competitions/{competitionId} competition updateCompetiton

Updated competition

This can only be done by admin.

*/
type UpdateCompetiton struct {
	Context *middleware.Context
	Handler UpdateCompetitonHandler
}

func (o *UpdateCompetiton) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateCompetitonParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
