// Code generated by go-swagger; DO NOT EDIT.

package range_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	models "github.com/krezac/los-server/models"
)

// GetRangeByIDOKCode is the HTTP code returned for type GetRangeByIDOK
const GetRangeByIDOKCode int = 200

/*GetRangeByIDOK successful operation

swagger:response getRangeByIdOK
*/
type GetRangeByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Range `json:"body,omitempty"`
}

// NewGetRangeByIDOK creates GetRangeByIDOK with default headers values
func NewGetRangeByIDOK() *GetRangeByIDOK {

	return &GetRangeByIDOK{}
}

// WithPayload adds the payload to the get range by Id o k response
func (o *GetRangeByIDOK) WithPayload(payload *models.Range) *GetRangeByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get range by Id o k response
func (o *GetRangeByIDOK) SetPayload(payload *models.Range) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRangeByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRangeByIDBadRequestCode is the HTTP code returned for type GetRangeByIDBadRequest
const GetRangeByIDBadRequestCode int = 400

/*GetRangeByIDBadRequest Invalid ID supplied

swagger:response getRangeByIdBadRequest
*/
type GetRangeByIDBadRequest struct {
}

// NewGetRangeByIDBadRequest creates GetRangeByIDBadRequest with default headers values
func NewGetRangeByIDBadRequest() *GetRangeByIDBadRequest {

	return &GetRangeByIDBadRequest{}
}

// WriteResponse to the client
func (o *GetRangeByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetRangeByIDNotFoundCode is the HTTP code returned for type GetRangeByIDNotFound
const GetRangeByIDNotFoundCode int = 404

/*GetRangeByIDNotFound Shooting range not found

swagger:response getRangeByIdNotFound
*/
type GetRangeByIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetRangeByIDNotFound creates GetRangeByIDNotFound with default headers values
func NewGetRangeByIDNotFound() *GetRangeByIDNotFound {

	return &GetRangeByIDNotFound{}
}

// WithPayload adds the payload to the get range by Id not found response
func (o *GetRangeByIDNotFound) WithPayload(payload *models.APIResponse) *GetRangeByIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get range by Id not found response
func (o *GetRangeByIDNotFound) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRangeByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
