// Code generated by go-swagger; DO NOT EDIT.

package range_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRangeByIDHandlerFunc turns a function with the right signature into a get range by Id handler
type GetRangeByIDHandlerFunc func(GetRangeByIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRangeByIDHandlerFunc) Handle(params GetRangeByIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetRangeByIDHandler interface for that can handle valid get range by Id params
type GetRangeByIDHandler interface {
	Handle(GetRangeByIDParams, interface{}) middleware.Responder
}

// NewGetRangeByID creates a new http.Handler for the get range by Id operation
func NewGetRangeByID(ctx *middleware.Context, handler GetRangeByIDHandler) *GetRangeByID {
	return &GetRangeByID{Context: ctx, Handler: handler}
}

/*GetRangeByID swagger:route GET /range/{rangeId} range getRangeById

Find shooting range by ID

Returns a single shooting range

*/
type GetRangeByID struct {
	Context *middleware.Context
	Handler GetRangeByIDHandler
}

func (o *GetRangeByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRangeByIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
