// Code generated by go-swagger; DO NOT EDIT.

package range_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/krezac/los-server/models"
)

// GetRangesOKCode is the HTTP code returned for type GetRangesOK
const GetRangesOKCode int = 200

/*GetRangesOK successful operation

swagger:response getRangesOK
*/
type GetRangesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Range `json:"body,omitempty"`
}

// NewGetRangesOK creates GetRangesOK with default headers values
func NewGetRangesOK() *GetRangesOK {

	return &GetRangesOK{}
}

// WithPayload adds the payload to the get ranges o k response
func (o *GetRangesOK) WithPayload(payload []*models.Range) *GetRangesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get ranges o k response
func (o *GetRangesOK) SetPayload(payload []*models.Range) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRangesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Range, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
